name: .NET Framework CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore "Main/CS455 Assignment 1.sln"

    - name: Build Solution
      run: msbuild "Main/CS455 Assignment 1.sln" /p:Configuration=Release

    - name: Run Tests
      run: |
        $testProjects = Get-ChildItem -Recurse **/*Tests*.csproj
        foreach ($testProject in $testProjects) {
          msbuild /t:VSTest $testProject.FullName
        }

